"""initial schema

Revision ID: 1c262eee4a92
Revises: 
Create Date: 2026-03-18 18:46:49.520941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c262eee4a92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=20), nullable=False),
    sa.Column('session', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('short_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number', 'session', name='uq_bill_session')
    )
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=False)
    op.create_index(op.f('ix_bills_session'), 'bills', ['session'], unique=False)
    op.create_table('bill_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.Enum('FLOOR_ACTION', 'COMMITTEE_ACTION', name='event_type_enum'), nullable=False),
    sa.Column('chamber', sa.Enum('HOUSE', 'SENATE', name='chamber_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'event_date', 'source_url', name='uq_bill_event')
    )
    op.create_table('bill_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=True),
    sa.Column('sponsor_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_event_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.Enum('HOUSE', 'SENATE', name='outcome_chamber_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome_type', sa.Enum('HEARD_AND_HELD', 'MOVED_OUT_OF_COMMITTEE', 'TABLED', 'DIED_IN_COMMITTEE', 'READ_ON_FLOOR', 'REFERRED_TO_COMMITTEE', 'RULES_TO_CALENDAR', 'AMENDED', 'PASSED', 'FAILED', 'TRANSMITTED', 'SIGNED_INTO_LAW', 'VETOED', 'POCKET_VETOED', 'OTHER', name='outcome_type_enum'), nullable=False),
    sa.Column('committee', sa.String(length=200), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['bill_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_event_outcomes')
    op.drop_table('bill_sponsors')
    op.drop_table('bill_events')
    op.drop_index(op.f('ix_bills_session'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
