"""replace_meeting_notes_bills_with_agenda_items

Revision ID: 34cf033cebe8
Revises: 3ef90762ed54
Create Date: 2026-03-22 23:22:06.586302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34cf033cebe8'
down_revision: Union[str, None] = '3ef90762ed54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bills_in_meeting_bill_id', table_name='bills_in_meeting')
    op.drop_index('ix_bills_in_meeting_meeting_id', table_name='bills_in_meeting')
    op.drop_table('bills_in_meeting')
    op.drop_index('ix_meeting_notes_meeting_id', table_name='meeting_notes')
    op.drop_table('meeting_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='meeting_notes_meeting_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='meeting_notes_pkey')
    )
    op.create_index('ix_meeting_notes_meeting_id', 'meeting_notes', ['meeting_id'], unique=False)
    op.create_table('bills_in_meeting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_teleconferenced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='bills_in_meeting_bill_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='bills_in_meeting_meeting_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bills_in_meeting_pkey'),
    sa.UniqueConstraint('meeting_id', 'bill_number', name='uq_meeting_bill')
    )
    op.create_index('ix_bills_in_meeting_meeting_id', 'bills_in_meeting', ['meeting_id'], unique=False)
    op.create_index('ix_bills_in_meeting_bill_id', 'bills_in_meeting', ['bill_id'], unique=False)
    # ### end Alembic commands ###
