"""add_prefix_to_agenda_items

Revision ID: 869cd2b04f48
Revises: 34cf033cebe8
Create Date: 2026-03-22 23:36:07.974956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869cd2b04f48'
down_revision: Union[str, None] = '34cf033cebe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_items', sa.Column('prefix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda_items', 'prefix')
    # ### end Alembic commands ###
