"""add is_tracked to bills

Revision ID: d20befb1cd2b
Revises: d04da9ae7129
Create Date: 2026-03-19 12:35:06.693539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20befb1cd2b'
down_revision: Union[str, None] = 'd04da9ae7129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('is_tracked', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'is_tracked')
    # ### end Alembic commands ###
